name: Metrics
on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: tarcisiobm
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          committer_branch: cards
          committer_message: "Update github-metrics.svg [Skip GitHub Action]"
          plugin_isocalendar: yes